"""empty message

Revision ID: 6707b5335f9d
Revises: 
Create Date: 2021-06-08 09:45:02.389656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6707b5335f9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('First name', sa.String(length=64), nullable=True),
    sa.Column('Last name', sa.String(length=64), nullable=True),
    sa.Column('Birthday', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=128), nullable=True),
    sa.Column('Price', sa.Float(), nullable=True),
    sa.Column('ISBN', sa.Integer(), nullable=True),
    sa.Column('Publication year', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ISBN')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=True),
    sa.Column('Password', sa.String(length=64), nullable=True),
    sa.Column('First name', sa.String(length=64), nullable=True),
    sa.Column('Last name', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=128), nullable=False),
    sa.Column('Is admin', sa.Boolean(), nullable=True),
    sa.Column('Is active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
